### ISSUE TITLE
New Microsoft Teams not supported.

### ISSUE THREAD

**Issue by RobertCSternberg** [ajobbins/AHK-Teams-Presence#3]
This project was built to support Microsoft Teams classic.  New Microsoft Teams is not currently supported.  

See more on versions of Microsoft Teams here https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin

**Comment by ajobbins** [comment]
A note has been added to the readme stating the project does not support the new teams, and wont at this stage unless someone can solve and submit a pull request.

**Comment by RobertCSternberg** [comment]
For those looking for a hit it looks like the new logs are stored here, by tenant.  \AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\WV2Profile_tfw\Service Worker\CacheStorage\

**Comment by RobertCSternberg** [comment]
For those looking for an alternative for the New Teams you can find the following Repo:
https://github.com/RobertCSternberg/AHK-New-Teams-Presence

#### Current reasons for not requesting a merge. 
- More detailed setup is required due to the New Teams log structure. 
- Webhook implementation was skipped so it is not a direct replacement for those using the project for home automation.
